import { Matter } from "../core/models/matter";
import { Group } from "../core/models/group";
import { Lesson } from "../core/models/lesson";
import { User } from "../auth/models/user";
import { Student } from "../core/models/student";
import { Score } from "../core/models/score";
import { Note } from "../core/models/note";

export const matterArr: Matter[] = [
      new Matter({
        id: '1',
        theme: 'Лин.анализ'
      }),
      new Matter({
        id: '2',
        theme: 'Теор.вер.'
      }),
      new Matter({
        id: '3',
        theme: 'Мат.стат.'
      }),
    ];

export const groupArr: Group[] = [
      new Group({
        id: '1',
        name: '110',
        studentIds: ['1', '2', '3', '4', '5'],
        lessonIds: ['1'],
      }),
      new Group({
        id: '2',
        name: '120',
        studentIds: ['6', '7', '8', '9', '10'],
        lessonIds: ['2'],
      }),
      new Group({
        id: '3',
        name: '130',
        studentIds: ['11', '12', '13', '14', '15'],
        lessonIds: ['3'],
      }),
    ];

const dateGenerator = (
  plusDays: number = 0,
  hours: number = 0,
  minutes: number = 0
): Date => {
  const now: Date = new Date();
  const days: number = now.getDate() + plusDays;

  return new Date(
    now.getFullYear(),
    now.getMonth(),
    days,
    hours,
    minutes
  );
};

export const lessonArr: Lesson[] = [
      new Lesson ({
        id: '1',
        themeId: '1',
        groupIds: ['1'],
        place: 'ауд. 215',
        date: dateGenerator(),
        subscription: '...',
      }),
      new Lesson ({
        id: '2',
        themeId: '2',
        place: 'ауд. 72',
        groupIds: ['1'],
        date: dateGenerator(1, 11, 0),
        subscription: '...',
      }),
      new Lesson ({
        id: '3',
        themeId: '1',
        place: 'ауд. 100-м',
        groupIds: '2',
        date: dateGenerator(2, 14, 0),
        subscription: '...',
      }),
      new Lesson ({
        id: '4',
        themeId: '3',
        place: 'ауд. 205',
        groupIds: ['3'],
        date: new Date(2017, 8, 30, 11, 30),
        subscription: '...',
      }),
    ];

export const user: User = new User ({
      id: '1',
      firstName: 'John',
      lastName: 'Doe',
      login: 'JohnDoe',
      pathHash: '9fd9f63e0d6487537569075da85a0c7f'// JohnDoe
    });

export const studentArr: Student[] = [
  new Student({
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    groupId: '1',
    scoreIds: ['1', '6', '11', '16', '21', '26', '31', '36'],
    noteIds: ['1', '4', '5', '6', '10', '11'],
  }),
  new Student({
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    groupId: '1',
    scoreIds: ['2', '7', '12', '17', '22', '27', '32', '37'],
    noteIds: ['2', '7'],
  }),
  new Student({
    id: '3',
    firstName: 'Adam',
    lastName: 'Morrison',
    groupId: '1',
    scoreIds: ['3', '8', '13', '18', '23', '28', '33', '38'],
    noteIds: [],
  }),
  new Student({
    id: '4',
    firstName: 'El',
    lastName: 'Davis',
    groupId: '1',
    scoreIds: ['4', '9', '14', '19', '24', '29', '34', '39'],
    noteIds: ['3', '8'],
  }),
  new Student({
    id: '5',
    firstName: 'Emmy',
    lastName: 'Hudson',
    groupId: '1',
    scoreIds: ['5', '10', '15', '20', '25', '30', '35', '40'],
    noteIds: ['9'],
  }),
  new Student({
    id: '6',
    firstName: 'Sara',
    lastName: 'Willow',
    groupId: '2',
    scoreIds: ['41', '46', '51'],
    noteIds: ['14', '15', '16'],
  }),
  new Student({
    id: '7',
    firstName: 'Rick',
    lastName: 'Sanchez',
    groupId: '2',
    scoreIds: ['42', '47', '52'],
    noteIds: ['12', '17'],
  }),
  new Student({
    id: '8',
    firstName: 'Morty',
    lastName: 'Smith',
    groupId: '2',
    scoreIds: ['43', '48', '53'],
    noteIds: [],
  }),
  new Student({
    id: '9',
    firstName: 'Harold',
    lastName: 'Alanson',
    groupId: '2',
    scoreIds: ['44', '49', '54'],
    noteIds: ['13', '18'],
  }),
  new Student({
    id: '10',
    firstName: 'Hugh',
    lastName: 'Lawson',
    groupId: '2',
    scoreIds: ['45', '50', '55'],
    noteIds: ['19'],
  }),
  new Student({
    id: '11',
    firstName: 'Sam',
    lastName: 'Stone',
    groupId: '3',
    scoreIds: [],
    noteIds: [],
  }),
  new Student({
    id: '12',
    firstName: 'Mathew',
    lastName: 'Backer',
    groupId: '3',
    scoreIds: [],
    noteIds: [],
  }),
  new Student({
    id: '13',
    firstName: 'Sam',
    lastName: 'Carrion',
    groupId: '3',
    scoreIds: [],
    noteIds: [],
  }),
  new Student({
    id: '14',
    firstName: 'Dave',
    lastName: 'Sandman',
    groupId: '3',
    scoreIds: [],
    noteIds: [],
  }),
  new Student({
    id: '15',
    firstName: 'Joe',
    lastName: 'Swanson',
    groupId: '3',
    scoreIds: [],
    noteIds: [],
  }),
];

export const scoreArr: Score[] = [
  new Score({
    id: '1',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 8, 25, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '2',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 8, 25, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '3',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 8, 25, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '4',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 8, 25, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '5',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 8, 25, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '6',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 8, 27, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '7',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 8, 27, 10, 0),
    type: 'score:4',
  }),
  new Score({
    id: '8',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 8, 27, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '9',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 8, 27, 10, 0),
    type: 'score:3',
  }),
  new Score({
    id: '10',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 8, 27, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '11',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 8, 29, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '12',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 8, 29, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '13',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 8, 29, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '14',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 8, 29, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '15',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 8, 29, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '16',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 2, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '17',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 9, 2, 10, 0),
    type: 'score:4',
  }),
  new Score({
    id: '18',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 9, 2, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '19',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 9, 2, 10, 0),
    type: 'not present',
  }),
  new Score({
    id: '20',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 9, 2, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '21',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 4, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '22',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 9, 4, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '23',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 9, 4, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '24',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 9, 4, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '25',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 9, 4, 10, 0),
    type: 'present',
  }),
  new Score({
    id: '26',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 6, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '27',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 9, 6, 10, 0),
    type: 'score:4',
  }),
  new Score({
    id: '28',
    themeId: '1',
    studentId: '3',
    date: new Date(2017, 9, 6, 10, 0),
    type: 'score:5',
  }),
  new Score({
    id: '29',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 9, 6, 10, 0),
    type: 'not present',
  }),
  new Score({
    id: '30',
    themeId: '1',
    studentId: '5',
    date: new Date(2017, 9, 6, 10, 0),
    type: 'not present',
  }),
  new Score({
    id: '31',
    themeId: '2',
    studentId: '1',
    date: new Date(2017, 8, 26, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '32',
    themeId: '2',
    studentId: '2',
    date: new Date(2017, 8, 26, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '33',
    themeId: '2',
    studentId: '3',
    date: new Date(2017, 8, 26, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '34',
    themeId: '2',
    studentId: '4',
    date: new Date(2017, 8, 26, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '35',
    themeId: '2',
    studentId: '5',
    date: new Date(2017, 8, 26, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '36',
    themeId: '2',
    studentId: '1',
    date: new Date(2017, 8, 28, 12, 30),
    type: 'score:5',
  }),
  new Score({
    id: '37',
    themeId: '2',
    studentId: '2',
    date: new Date(2017, 8, 28, 12, 30),
    type: 'score:4',
  }),
  new Score({
    id: '38',
    themeId: '2',
    studentId: '3',
    date: new Date(2017, 8, 28, 12, 30),
    type: 'score:5',
  }),
  new Score({
    id: '39',
    themeId: '2',
    studentId: '4',
    date: new Date(2017, 8, 28, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '40',
    themeId: '2',
    studentId: '5',
    date: new Date(2017, 8, 28, 12, 30),
    type: 'present',
  }),
  new Score({
    id: '41',
    themeId: '1',
    studentId: '6',
    date: new Date(2017, 8, 26, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '42',
    themeId: '1',
    studentId: '7',
    date: new Date(2017, 8, 26, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '43',
    themeId: '1',
    studentId: '8',
    date: new Date(2017, 8, 26, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '44',
    themeId: '1',
    studentId: '9',
    date: new Date(2017, 8, 26, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '45',
    themeId: '1',
    studentId: '10',
    date: new Date(2017, 8, 26, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '46',
    themeId: '1',
    studentId: '6',
    date: new Date(2017, 8, 26, 15, 0),
    type: 'score:5',
  }),
  new Score({
    id: '47',
    themeId: '1',
    studentId: '7',
    date: new Date(2017, 8, 26, 15, 0),
    type: 'score:4',
  }),
  new Score({
    id: '48',
    themeId: '1',
    studentId: '8',
    date: new Date(2017, 8, 26, 15, 0),
    type: 'score:5',
  }),
  new Score({
    id: '49',
    themeId: '1',
    studentId: '9',
    date: new Date(2017, 8, 26, 15, 0),
    type: 'present',
  }),
  new Score({
    id: '50',
    themeId: '1',
    studentId: '10',
    date: new Date(2017, 8, 26, 15, 0),
    type: 'present',
  }),
  new Score({
    id: '51',
    themeId: '1',
    studentId: '6',
    date: new Date(2017, 8, 28, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '52',
    themeId: '1',
    studentId: '7',
    date: new Date(2017, 8, 28, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '53',
    themeId: '1',
    studentId: '8',
    date: new Date(2017, 8, 28, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '54',
    themeId: '1',
    studentId: '9',
    date: new Date(2017, 8, 28, 13, 0),
    type: 'present',
  }),
  new Score({
    id: '55',
    themeId: '1',
    studentId: '10',
    date: new Date(2017, 8, 28, 13, 0),
    type: 'present',
  }),
];

export const noteArr: Note[] = [
  new Note({
    id: '1',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'Определите уравнение корреляционной зависимости, коэффициент корреляции на основе данных. Задача 107.',
  }),
  new Note({
    id: '2',
    themeId: '1',
    studentId: '2',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '3',
    themeId: '1',
    studentId: '4',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 3',
  }),
  new Note({
    id: '4',
    themeId: '2',
    studentId: '1',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '5',
    themeId: '2',
    studentId: '1',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '6',
    themeId: '2',
    studentId: '1',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 3',
  }),
  new Note({
    id: '7',
    themeId: '3',
    studentId: '2',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '8',
    themeId: '3',
    studentId: '4',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '9',
    themeId: '3',
    studentId: '5',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 3',
  }),
  new Note({
    id: '10',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '11',
    themeId: '1',
    studentId: '1',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '12',
    themeId: '1',
    studentId: '7',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '13',
    themeId: '1',
    studentId: '9',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 3',
  }),
  new Note({
    id: '14',
    themeId: '2',
    studentId: '6',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '15',
    themeId: '2',
    studentId: '6',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '16',
    themeId: '2',
    studentId: '6',
    date: new Date(2017, 9, 26, 10, 0),
    text: 'note 3',
  }),
  new Note({
    id: '17',
    themeId: '3',
    studentId: '7',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 1',
  }),
  new Note({
    id: '18',
    themeId: '3',
    studentId: '9',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 2',
  }),
  new Note({
    id: '19',
    themeId: '3',
    studentId: '10',
    date: new Date(2017, 9, 25, 10, 0),
    text: 'note 3',
  }),
];

export const filterData: any = {
  groupId: '1',
  matterId: '1',
};

